// Package telemetry 暴露 Prometheus 指标（服务端），遵循 RED 方法：
// Rate（每秒请求数）、Errors（每秒失败请求数）、Duration（延迟直方图，
// P50/P95/P99 分桶）。导入 "github.com/prometheus/client_golang/prometheus/promhttp"
// 可暴露 /metrics 端点。
//
// 参考：Google SRE Book 第 6 章《监控分布式系统》。
package telemetry

import (
	"context"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// namespace 是所有指标的前缀，遵循 Prometheus 命名规范。
const (
	namespace = "ydsz"
	subsystem = "http"
)

var (
	// RequestTotal 按 method / route / status 统计请求总数。
	RequestTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: subsystem,
			Name:      "request_total",
			Help:      "Total HTTP requests.",
		},
		[]string{"method", "route", "status"},
	)

	// RequestDurationMs 记录请求延迟分布。
	RequestDurationMs = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: subsystem,
			Name:      "request_duration_ms",
			Help:      "HTTP request latency distribution.",
			Buckets:   prometheus.DefBuckets, // .005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10
		},
		[]string{"method", "route"},
	)

	// DBDurationMs 记录数据库查询延迟（由服务层手动调用埋点）。
	DBDurationMs = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Namespace: namespace,
			Name:      "db_query_duration_ms",
			Help:      "Database query latency distribution.",
			Buckets:   []float64{1, 5, 10, 25, 50, 100, 250, 500, 1000, 5000},
		},
		[]string{"operation"},
	)

	// RedisPublished 统计转发到 Redis Streams 的 outbox 事件（成功/失败）。
	RedisPublished = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "redis_events_published_total",
			Help:      "Outbox events relayed to Redis Streams.",
		},
		[]string{"status"},
	)

	// AuthOperations 统计注册/登录/刷新结果。
	AuthOperations = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "auth_operations_total",
			Help:      "Authentication operations.",
		},
		[]string{"operation", "status"},
	)

	// VersionOperations 统计版本 CRUD 与生命周期操作结果。
	// 维度 labels: operation=create|update|delete|active|released|archived, status=success|error。
	VersionOperations = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "version_operations_total",
			Help:      "Version CRUD and lifecycle operations.",
		},
		[]string{"operation", "status"},
	)

	// NotificationCreated 统计按渠道聚合的通知生成数量（含去重）。
	// 维度 labels: channel=in_app|email|wecom|dingtalk|feishu, status=created|deduped|error。
	NotificationCreated = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "notification_created_total",
			Help:      "Notifications generated by channel (includes deduped).",
		},
		[]string{"channel", "status"},
	)

	// NotificationDelivered 统计实际投递到外部渠道的成功与失败数。
	// 维度 labels: channel=email|wecom|dingtalk|feishu, status=sent|failed。
	NotificationDelivered = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "notification_delivered_total",
			Help:      "Notifications dispatched to external channels.",
		},
		[]string{"channel", "status"},
	)

	// NotificationDispatchDuration 投递到外部渠道的耗时（含网络 I/O）。
	NotificationDispatchDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Namespace: namespace,
			Name:      "notification_dispatch_duration_ms",
			Help:      "Time to dispatch a notification to an external channel.",
			Buckets:   []float64{10, 50, 100, 250, 500, 1000, 2500, 5000, 10000},
		},
		[]string{"channel"},
	)

	// WSConnections 是当前所有节点上活跃的 WebSocket 连接总数（Gauge）。
	WSConnections = promauto.NewGauge(
		prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "ws_active_connections",
			Help:      "Current number of active WebSocket connections across all nodes.",
		},
	)

	// AIOperations 记录 AI 端点调用次数（包含降级来源）。
	// 维度 labels: operation=smart_assign|detect_duplicates|classify|summarize,
	//            source=llm|rule_engine|unavailable, status=success|error。
	AIOperations = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "ai_operations_total",
			Help:      "AI endpoint invocations, tagged by operation and source (llm / rule_engine / unavailable).",
		},
		[]string{"operation", "source", "status"},
	)

	// AIDurationMs 记录 AI 端点耗时（LLM 远端调用或规则引擎计算）。
	AIDurationMs = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Namespace: namespace,
			Name:      "ai_duration_ms",
			Help:      "AI endpoint latency distribution.",
			Buckets:   []float64{1, 5, 10, 25, 50, 100, 250, 500, 1000, 3000, 10000},
		},
		[]string{"operation"},
	)

// AIFallbacks 记录 AI 从 LLM fallback 到规则引擎的次数。
AIFallbacks = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "ai_fallbacks_total",
			Help:      "Count of AI operations that fell back to rule engine (provider unavailable or errored).",
		},
		[]string{"operation"},
	)
)

// ---------------------------------------------------------------------------
// P1-6: DB 连接池 Prometheus 指标（Google SRE 第 6 章 — 导出关键资源利用率）
// ---------------------------------------------------------------------------

// planeDbPool 指标变量（延迟注册，由 PoolStatsCollector 在 Start 时写入）。
// 使用独立的注册逻辑以避免与 promauto 的全局 Registry 冲突。
var (
	dbPoolTotalConns = promauto.NewGauge(
		prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "db_pool_total_connections",
			Help:      "Total number of connections in the database pool.",
		},
	)

	dbPoolIdleConns = promauto.NewGauge(
		prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "db_pool_idle_connections",
			Help:      "Current number of idle connections in the database pool.",
		},
	)

	dbPoolAcquireCount = promauto.NewCounter(
		prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "db_pool_acquire_count",
			Help:      "Total number of connection acquires from the pool.",
		},
	)

	dbPoolAcquireDuration = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Namespace: namespace,
			Name:      "db_pool_acquire_duration_seconds",
			Help:      "Histogram of connection acquisition durations from the pool.",
			Buckets:   []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0},
		},
	)

	dbPoolAcquireTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "db_pool_acquire_total",
			Help:      "Total number of successful connection acquires.",
		},
	)
)

// PoolStatsCollector 包装 *pgxpool.Pool 并按固定间隔采集连接池指标。
// Uber Go Style Guide: "Use types to expose behavior, not just data."
//
// 使用方式：
//
//	collector := telemetry.NewPoolStatsCollector(pool)
//	ticker := time.NewTicker(15 * time.Second)
//	go collector.Start(ctx, ticker)
//	defer ticker.Stop()
type PoolStatsCollector struct {
	pool *pgxpool.Pool
}

// NewPoolStatsCollector 构造一个连接池指标采集器。
func NewPoolStatsCollector(pool *pgxpool.Pool) *PoolStatsCollector {
	return &PoolStatsCollector{pool: pool}
}

// Collect 执行一次指标采集（导出到 Prometheus 寄存器）。
// 对标 Google SRE "Four Golden Signals" 中的 Saturation：
// 连接池接近上限时，acquire 延迟会显著上升，是容量规划的早期信号。
func (c *PoolStatsCollector) Collect() {
	if c.pool == nil {
		return
	}
	stat := c.pool.Stat()
	dbPoolTotalConns.Set(float64(stat.MaxConns()))
	dbPoolIdleConns.Set(float64(stat.IdleConns()))
	dbPoolAcquireCount.Add(float64(stat.AcquireCount()))
	dbPoolAcquireDuration.Observe(stat.AcquireDuration().Seconds())
	dbPoolAcquireTotal.Add(float64(stat.AcquireCount()))
}

// Start 在后台按 ticker 周期采集，ctx 取消时退出。
// Uber Go Style: "Goroutines should be cleaned up when no longer needed."
func (c *PoolStatsCollector) Start(ctx context.Context, ticker *time.Ticker) {
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			c.Collect()
		}
	}
}

// MetricsMiddleware 为每个请求记录 request_total 与 request_duration_ms。
// 它提取匹配的路由模式（c.FullPath()），使形如
// /api/v1/workspaces/{slug}/issues/123 的路径坍缩为同一组标签序列。
func MetricsMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		start := time.Now()
		c.Next()
		latency := float64(time.Since(start).Milliseconds())

		route := c.FullPath()
		if route == "" {
			route = "unmatched"
		}
		status := classStatus(c.Writer.Status())
		RequestTotal.WithLabelValues(c.Request.Method, route, status).Inc()
		RequestDurationMs.WithLabelValues(c.Request.Method, route).Observe(latency)
	}
}

// classStatus 将 HTTP 状态码映射为粗粒度标签 "2xx".."5xx"。
func classStatus(code int) string {
	switch {
	case code < 200:
		return "1xx"
	case code < 300:
		return "2xx"
	case code < 400:
		return "3xx"
	case code < 500:
		return "4xx"
	default:
		return "5xx"
	}
}
