run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gofmt
    - revive
    - gocritic
    - misspell

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
  errcheck:
    check-blank: false

issues:
  exclude-rules:
    - path: _test\.go
      linters: [errcheck]
  max-issues-per-linter: 0
  max-same-issues: 0
